version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.2
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys:
          fingerprints:
            - "SHA256:WpdywTpdxwyZ6oKW9eI7nTlDMY8AklGUfIDIosVlbd4"

      - run:
          name: Deploy to EC2 via SSH
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
              cd /home/ubuntu/webrtc-video-call-example-nodejs
              git pull origin main
              npm install
              pm2 restart webrtc || pm2 start index.js --name webrtc
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
